### ISSUE TITLE
crash while running jmx_detector_analysis.py

### ISSUE THREAD

**Issue by berndporr** [eleanorforsyth/JMX-ECG-Benchmark#1]
Looks like the template file for the Matched Filter Detector is missing in this repo:
```
nalysing subject 22, jogging, chest_strap_V2_V1
pan_tompkins_detector done
Analysing subject 23, jogging, chest_strap_V2_V1
pan_tompkins_detector done
Analysing subject 24, jogging, chest_strap_V2_V1
pan_tompkins_detector done
Analysing subject 0, sitting, einthoven_ii
Traceback (most recent call last):
  File "./jmx_detector_analysis.py", line 276, in <module>
    detected_peaks = detectors.matched_filter_detector(data, template_name)
  File "/home/bp1/.local/lib/python3.8/site-packages/ecgdetectors.py", line 376, in matched_filter_detector
    template = np.loadtxt(template_file)
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 968, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/lib/python3/dist-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/lib/python3/dist-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: templates/sitting_Sub0_einthoven_ii_PQRSTave_44.csv not found.
```

**Comment by eleanorforsyth** [comment]
Zip file is now uploaded containing the templates. Needs to be unzipped and placed in the working directory and should run:)

**Comment by berndporr** [comment]
Can you add this in the unzipped state to the working dir and commit.
